version: "2.1"
services:

  broker:
    image: emqx/emqx:latest
    ports:
      - 18083:18083
      - 1883:1883
    # build:
    #   context: .
    #   dockerfile: snowbot/Dockerfile
    # stop_signal: SIGINT
    # network_mode: host
    # privileged: true
    # command: snowbot -v
    # volumes:
    #   - ./data/:/app/data/
    #   - ~/.aws:/app/.aws   # Move this to a different dir, or disable it

    #   # Tests
    #   - ./snowbot/tests/:/app/snowbot/tests/

    #   #  Mappings
    #   - ./common/common/:/app/common/common/
    #   - ./common/properties.yaml:/app/common/properties.yaml
    #   - ./snowbot/snowbot/:/app/snowbot/snowbot/
    #   - ./snowbot/base-settings.yaml:/app/snowbot/base-settings.yaml
    #   - ./snowbot/properties.yaml:/app/snowbot/properties.yaml
    # depends_on:
    #   - mqtt
    #   - roc-client
